databaseChangeLog:
  -  preConditions:
  -  runningAs:
       username:  root
  - changeSet:
      id: 5
      author: rahman
      changes:
        - loadData:
            catalogName: employeemanager
            columns:
              - column:
                  header: header1
                  name: id
                  type: NUMERIC
              - column:
                  index: 1
                  name: email
                  type: STRING
              - column:
                  index: 2
                  name:  employee_code
                  type: STRING
              - column:
                  index: 3
                  name: img_url
                  type: STRING
              - column:
                  index: 4
                  name:  job_title
                  type: STRING
              - column:
                  index: 5
                  name: name
                  type: STRING
              - column:
                  index: 6
                  name: phone
                  type: STRING
            commentLineStartsWith: //
            encoding: UTF-8
            file: ./employees.csv
            quotchar: ''''
            relativeToChangelogFile: true
            schemaName: employeemanager
            separator: ','
            tableName: employee
            usePreparedStatements: true